[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-added-large-files"

[[repos.hooks]]
id = "check-symlinks"


[[repos]]
repo = "local"

[[repos.hooks]]
id = "update-present-blocks-in-readme"
name = "update `present` blocks in README.md"
language = "system"
entry = "present --in-place README.md"
pass_filenames = false

[[repos.hooks]]
id = "cargo-fmt"
name = "format code"
language = "system"
entry = "cargo fmt"
pass_filenames = false
